# Generated by Django 2.2 on 2021-10-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deskbuddy', '0002_photo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
    ]
